- name: Configure webserver with nginx
  hosts: ubuntus
  become: False
  vars:
    message: "Hello world {{inventory_hostname}}"
  tasks:
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
      notify: restart nginx

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
